/**
 * coldharbour/layout.ts — THE MAP, as data: structure placements, scatter
 * regions, control points, spawns, the two vehicle hardstandings, the lawns and
 * the water. GENERATED by `scripts/generate-coldharbour.mjs`
 * (`npm run coldharbour`) — the design is authored there and transcribed here
 * mechanically, with every placement checked against the floor, the roads and
 * its own front door. The editor opens, patches and saves this file like any
 * other; re-running the generator DISCARDS those edits.
 *
 * Consumed by MapBuilder; nothing here is code to special-case.
 * Gotchas that have already cost time: collider top faces within
 * CONFIG.nav.stepHeight of adjacent ground or bots treat decks as walls;
 * a control point's pos must NOT sit inside a collider (surfaceAt returns -1);
 * scatter clearance values must match prop collider extents.
 */
import { Vector3 } from "@babylonjs/core";
import type {
  ControlPointDef,
  GrassRect,
  MapLayout,
  Placement,
  ScatterSpec,
  SpawnPointDef,
  VehicleSpawnDef,
  WaterRect,
} from "../layout";

/**
 * COLDHARBOUR — a harbour town on a bay, an hour before dusk, with the
 * fighting in its streets.
 *
 * **320 x 320 m**, origin at the map centre, +Z is north. The town is a
 * horseshoe round its harbour: the quays at the bottom, the civic square at
 * the harbour's head, the old town and the fish quay on the west shore, the
 * docks and the goods yard on the east, and the commercial town climbing the
 * hill behind to the ridge road along the top.
 *
 *      z=+160  +---------------------------------------------------------+
 *              | HEIGHTS (T0) |   the ridge: High Street's tall stock   NE |
 *              |   home yard  |============ High Street ================|
 *              |  West   A  the Exchange    midtown     D  the Terminal  |
 *              |  Road   (+3.4)            (+2.4)        (train shed)    |
 *      z= +40  |  ====== Exchange St == Market St ===== Station Approach |
 *              |  old town   chapel   C  the square    east town  Station|
 *              |  (+0.3)     Fore St    the memorial   (+0.6)      Road  |
 *      z= -26  |  ....... Harbour Road (head) ......................     |
 *              |  B the car park |  ~~~~~ THE HARBOUR ~~~~~ |  E  the    |
 *              |   Ship Lane     |  ~~ boats on the mud ~~  |  Harbour   |
 *              |  ===== Strand ==|  ~~~~~~~~~~~~~~~~~~~~~~~ |  Board     |
 *              |  the Ness, net  |~~~~ wadeable at low ~~~~ | docks,     |
 *              |  lofts, racks   ~~~~~ water ~~~~~~~~~~~~~~ ~the Hard     |
 *      z=-152  |  ====== the pier =====[light]   mouth     ==== dock front|
 *              |~~~~~~~~~~~~~~~~~~~~~~~~ THE SEA ~~~~~~~~~~~~~~~~~ (T1) ~~~|
 *             x=-160          -50            0             46          +160
 *
 * **It was a business district on a 5 x 5 grid of 16 m avenues**, every one
 * of them 300 m long and dead straight, with a quay laid along the southern
 * edge after the fact. It played as eight lanes of fire between boxes and it
 * read as a diagram of a city. Everything about it that was a decision has
 * been kept — the five objectives and what each one is, the two home corners
 * on the NW-SE diagonal the sun's azimuth is chosen against, the hour, the
 * hills on three sides and the sea on the fourth — and the ground, the water
 * and the streets under them are new.
 *
 * ## The harbour, which is what the map is about now
 *
 * The bay cuts into the middle of the southern side: sixty metres across at
 * its head under the square, a hundred at the mouth and a hundred and ten from
 * one to the other, quayed round its head and down both sides, with the pier
 * and the harbour light on its head closing it from the west. **It is
 * WADEABLE everywhere inside the pier** — this engine has no swimming, so the
 * whole harbour is cut to low water, 0.7 m at the head and 1.1 at the mouth —
 * and the boats lie over on the mud beside the quays, which is the strongest
 * single thing on the map saying where it is.
 *
 * **What the water does to the fight is the point of it.** It is the one
 * stretch of open ground on the map a body crosses slowly and with nothing
 * but the boats for cover, overlooked from three quays, the square and the
 * car park's decks — and it is the short way between the two halves of the
 * town. Team 1 wades it from the Hard to reach B; team 0 walks round the
 * head for E or wades it the other way. The quays are cliffs the nav graph
 * severs, which is why the Strand and the Hard are natural foreshores: two
 * places a body walks out of the water, and the mouth between them a wade.
 *
 * ## What each flag is, and why they are five different things
 *
 * - **A, the Exchange** — a three-storey office on its own square at the top
 *   of Fore Street, with a garden behind. Three walked floors and a window band
 *   on three bearings over the High Town, approached up the West Road, up Fore
 *   Street or down from High Street.
 * - **B, the car park** — three open decks on the old fish market's site,
 *   between the west quay and Ship Lane. Every deck shoots every other, and
 *   the top one looks across the harbour at E. Covered on every side — the
 *   Strand's terrace, the lanes, the quay — so it is the brawl the open water
 *   beside it is not.
 * - **C, the civic square** — a lawn at the head of the harbour with four
 *   paths to the memorial, four stands of trees and the Town Hall on its
 *   corner. Five ways in, one of them the quay, and the trees are the only
 *   cover that is not furniture: the one you take last and lose first.
 * - **D, the Terminal** — the station forecourt under the train shed's arches,
 *   taxis on the rank and no interior at all. The fast flag.
 * - **E, the Harbour Board** — three walked floors at the head of the docks,
 *   its plaza onto Rope Street and its yard onto Warehouse Lane, overlooking
 *   the east quay and the harbour.
 *
 * ## The sightlines
 *
 * **No street runs the width of the map.** The cross-town line jogs at Fore
 * Street and at Quay Street, High Street jogs at both, Fore Street bends where
 * it reaches the High Town, and the two home roads jog twice each — so the
 * longest look down a street is about a hundred metres, against the three
 * hundred every avenue used to be. The long looks left are ACROSS the harbour
 * and down it to the sea, which is what a DMR on this map is for now.
 * `bots.perception.engageRange` is 55 m and did not move with the fog, so a
 * bot will not open up across the harbour the way a player will.
 *
 * ## What it costs
 *
 * **The collision bake roughly doubled — 800 boxes to 1,764 — and the frame
 * did not notice**, because no ray in the game walks the scene any more
 * (`RayWorld` answers analytically off bucketed boxes): measured uncapped on
 * the Windows box at the same five standing vantages before and after, the
 * square 370 -> 362 fps, the Exchange 250 -> 272, the car park 319 -> 373,
 * the forecourt 279 -> 249 and the Harbour Board 254 -> 246, with the build
 * 6.9 -> 8.2 s. What spent it is the old town: forty-odd jettied houses, an
 * inn and a church, each a handful of colliders, where the old map had
 * forty-four three-box towers. The light budget is twenty-two fixtures' worth
 * against the sixteen slots, spread so that no flag has more than its own:
 * the square's four lamps, the forecourt's two, one lamp each at A, B and E,
 * the two offices', the train shed's and a warehouse's windows, four lit
 * shops, the Anchor, the church and the harbour light.
 *
 * ## Layout hygiene (keep to these)
 *
 * - Structures are axis-aligned (`rotY` in multiples of pi/2), and the CITY
 *   kit's street front is its local +Z — the reverse of the village kit's.
 * - Nothing but kerb furniture stands in a carriageway, and a through road
 *   keeps one side clear of parked cars so a hull still has the other.
 * - Every quay stands on the line the floor's cliff is cut on; move one and
 *   the cliff stays where it was. Re-lay them in the generator.
 */

const placements: Placement[] = [
  // ===== roads =====================================================================
  // Visual only: a road carries no collider, stops no round and is in no
  // baked structure. The through roads are asphalt and the old town's lanes
  // and the square's paths are cobble. Every street is a PATH, so where two
  // meet the network paves the junction itself.
  // The Harbour Road: up the west quay from the Strand, round the head under the square and down the east quay to the docks.
  { kind: "road", x: -2, z: -71, params: { path: [[-48, -25], [-48, 45], [48, 45], [48, -45]], width: 11, surface: "asphalt", radius: 12 } },
  // The Strand Road, along the top of the foreshore to the old town's west end.
  { kind: "road", x: -91, z: -96, params: { path: [[41, 0], [-41, 0]], width: 9, surface: "asphalt" } },
  // The Dock Road, behind the cranes, out to the goods yard.
  { kind: "road", x: 83, z: -116, params: { path: [[-37, 0], [37, 0]], width: 11, surface: "asphalt" } },
  // The West Road: down from the Heights past the High Town and the old town to the Strand. Team 0's road.
  { kind: "road", x: -128, z: 14, params: { path: [[-4, 110], [-4, 48], [4, 38], [4, -38], [-4, -48], [-4, -110]], width: 11, surface: "asphalt", radius: 14 } },
  // The Station Road: up from the goods yard past the docks and the east town to the station. Team 1's road.
  { kind: "road", x: 116, z: 4, params: { path: [[4, -120], [4, -48], [-4, -38], [-4, 22], [4, 32], [4, 120]], width: 11, surface: "asphalt", radius: 14 } },
  // Fore Street, the old town's high street: up from the harbour head, bending into the High Town.
  { kind: "road", x: -54, z: 37, params: { path: [[4, -63], [4, -3], [-4, 9], [-4, 63]], width: 9, surface: "asphalt", radius: 10 } },
  // Quay Street, up from the east quay past the square to High Street.
  { kind: "road", x: 46, z: 41, params: { path: [[0, -67], [0, 67]], width: 9, surface: "asphalt" } },
  // Queen Street, north out of the square to High Street.
  { kind: "road", x: 0, z: 67, params: { path: [[0, -41], [0, 41]], width: 9, surface: "asphalt" } },
  // Exchange Street, across the High Town's foot from the West Road to Fore Street.
  { kind: "road", x: -87, z: 40, params: { path: [[-37, 0], [37, 0]], width: 9, surface: "asphalt" } },
  // Market Street, along the top of the square.
  { kind: "road", x: -2, z: 34, params: { path: [[-48, 0], [48, 0]], width: 9, surface: "asphalt" } },
  // Station Approach, from Quay Street to the Station Road past the forecourt.
  { kind: "road", x: 83, z: 40, params: { path: [[-37, 0], [37, 0]], width: 9, surface: "asphalt" } },
  // High Street, the ridge road along the top of the town, jogging at Fore Street and Quay Street.
  { kind: "road", x: -6, z: 104, params: { path: [[-126, -4], [-52, -4], [-42, 4], [42, 4], [52, -4], [126, -4]], width: 9, surface: "asphalt", radius: 8 } },
  // Warehouse Lane, across the docks behind the Harbour Board.
  { kind: "road", x: 83, z: -80, params: { path: [[-37, 0], [37, 0]], width: 9, surface: "asphalt" } },
  // Rope Street, across the east town.
  { kind: "road", x: 79, z: -8, params: { path: [[-33, 0], [33, 0]], width: 9, surface: "asphalt" } },
  // Ship Lane, the old town's back lane, from the Strand up to Exchange Street.
  { kind: "road", x: -96, z: -28, params: { path: [[0, -68], [0, 68]], width: 6, surface: "cobble" } },
  // Fish Lane and Chapel Lane, across the old town.
  { kind: "road", x: -87, z: -50, params: { path: [[-37, 0], [37, 0]], width: 6, surface: "cobble" } },
  { kind: "road", x: -87, z: 0, params: { path: [[-37, 0], [37, 0]], width: 6, surface: "cobble" } },
  // The square's four paths, out from the monument to the kerbs.
  { kind: "road", x: 0, z: 15.85, params: { length: 20.3, width: 4, surface: "cobble" } },
  { kind: "road", x: 0, z: -11.85, params: { length: 12.3, width: 4, surface: "cobble" } },
  { kind: "road", x: 13.85, z: 0, rotY: Math.PI / 2, params: { length: 16.3, width: 4, surface: "cobble" } },
  { kind: "road", x: -13.85, z: 0, rotY: Math.PI / 2, params: { length: 16.3, width: 4, surface: "cobble" } },
  // ===== the waterfront ============================================================
  // **Every quay stands on the line the floor's own cliff is cut on** (`QUAYS`
  // in the generator, which the heightfield is cut against): a quay hangs DOWN
  // from the ground at its origin, so the street runs on over the drop. The
  // runs touch end to end, and where two walls meet the deck of one covers the
  // corner. The parapet is 1.0 m, under `cover.crouchHeight` — it steers a body
  // and stops nothing, and a player can hop it into the harbour, which is
  // wadeable everywhere inside the pier.
  { kind: "quay", x: -20, z: -36, params: { length: 32 } },
  { kind: "quay", x: 12, z: -36, params: { length: 32 } },
  { kind: "quay", x: -40, z: -81, rotY: -Math.PI / 2, params: { length: 30 } },
  { kind: "quay", x: -40, z: -51, rotY: -Math.PI / 2, params: { length: 30 } },
  { kind: "quay", x: 32, z: -90, rotY: Math.PI / 2, params: { length: 36 } },
  { kind: "quay", x: 32, z: -54, rotY: Math.PI / 2, params: { length: 36 } },
  { kind: "quay", x: -142.67, z: -152, params: { length: 34.67 } },
  { kind: "quay", x: -108, z: -152, params: { length: 34.67 } },
  { kind: "quay", x: -73.33, z: -152, params: { length: 34.67 } },
  { kind: "quay", x: -60, z: -146, rotY: -Math.PI / 2, params: { length: 12 } },
  { kind: "quay", x: 76.67, z: -152, params: { length: 33.33 } },
  { kind: "quay", x: 110, z: -152, params: { length: 33.33 } },
  { kind: "quay", x: 143.33, z: -152, params: { length: 33.33 } },
  // THE HARBOUR LIGHT, on the pier head with its keeper's cottage turned back
  // along the pier toward the town. Not climbable (see `kit/harbour.ts`): a
  // gallery over a harbour every flag can see is a perch with no counter. It is
  // one of the sixteen light slots, always, and the one every bearing in the
  // town has a line to.
  { kind: "lighthouse", x: -71, z: -145, rotY: Math.PI / 2 },
  // The boats, lying over on the mud at low water — the strongest thing on the
  // map saying what the map is. Each one is solid and is cover a body wading
  // the harbour can reach.
  { kind: "careenedHull", x: -28, z: -66, params: { length: 11 } },
  { kind: "careenedHull", x: -27, z: -86, params: { length: 9 } },
  { kind: "careenedHull", x: -8, z: -48, rotY: Math.PI / 2, params: { length: 12 } },
  { kind: "careenedHull", x: 16, z: -62, params: { length: 10 } },
  { kind: "careenedHull", x: 20, z: -92, params: { length: 11 } },
  { kind: "careenedHull", x: -14, z: -112, rotY: Math.PI / 2, params: { length: 12 } },
  { kind: "careenedHull", x: -50, z: -122, rotY: Math.PI / 2, params: { length: 9 } },
  { kind: "careenedHull", x: 8, z: -130, params: { length: 10 } },
  { kind: "careenedHull", x: 52, z: -134, params: { length: 12 } },
  { kind: "careenedHull", x: 46, z: -146, rotY: Math.PI / 2, params: { length: 10 } },
  // Jetties off the two foreshores, their decks level with the beach top.
  { kind: "jetty", x: -66, z: -111, y: 1.73, params: { length: 18 } },
  { kind: "jetty", x: -84, z: -118, y: 1.28, params: { length: 14 } },
  // ===== C: the civic square =======================================================
  // The square at the head of the harbour: a lawn with four paths to the
  // memorial in the middle of it, four stands of trees for cover, and the Town
  // Hall and two terraces of shops turned to face it. It opens onto the
  // harbour on its fourth side, so the quay is part of the fight for it.
  { kind: "monument", x: 0, z: 0, params: { width: 11 } },
  { kind: "planter", x: -15, z: 5.5, params: { width: 2.6, depth: 1.4 } },
  { kind: "planter", x: 15, z: -6.5, params: { width: 2.6, depth: 1.4 } },
  { kind: "planter", x: 6, z: 15, rotY: Math.PI / 2, params: { width: 2.6, depth: 1.4 } },
  { kind: "planter", x: -6.5, z: -14, rotY: Math.PI / 2, params: { width: 2.6, depth: 1.4 } },
  { kind: "barrier", x: -12.5, z: -11, rotY: Math.PI / 2, params: { length: 6 } },
  { kind: "barrier", x: 11, z: 12, rotY: Math.PI / 2, params: { length: 6 } },
  { kind: "streetLight", x: -3.2, z: 21.5, params: { height: 7.5, lit: true } },
  { kind: "streetLight", x: 3.2, z: -14.5, rotY: Math.PI, params: { height: 7.5, lit: true } },
  { kind: "streetLight", x: -20.5, z: 3.2, rotY: Math.PI / 2, params: { height: 7.5, lit: true } },
  { kind: "streetLight", x: 20.5, z: -3.2, rotY: -Math.PI / 2, params: { height: 7.5, lit: true } },
  // The Town Hall, at the square's north-west corner, its lobby to the square.
  { kind: "tower", x: -34.4, z: 13.5, rotY: Math.PI / 2, params: { width: 18, depth: 17, height: 24 } },
  { kind: "shophouse", x: -31.6, z: -6.15, rotY: Math.PI / 2, params: { width: 11.1, depth: 15.6, floors: 2, tint: "#4a5a4a", sign: "#ff5f7a" } },
  { kind: "shophouse", x: 31, z: -5.05, rotY: -Math.PI / 2, params: { width: 11.5, depth: 15.6, floors: 3, tint: "#4a5a4a" } },
  { kind: "shophouse", x: 31, z: 7.75, rotY: -Math.PI / 2, params: { width: 11.1, depth: 15.6, floors: 2, tint: "#2f4a5c", sign: "#c46cff" } },
  { kind: "shophouse", x: 31.05, z: 20.25, rotY: -Math.PI / 2, params: { width: 10.9, depth: 15.7, floors: 2, tint: "#6a3a3a", litWindows: true } },
  // ===== B: the old town ===========================================================
  // The oldest part of the town, behind the west quay: the car park on the old
  // fish market's site, the Mariners' Church at the top of Ship Lane, the
  // Anchor on the Strand, and lanes of fishermen's houses packed between them.
  // B is the car park, and its approaches are covered on every side — the
  // Strand's terrace, the lanes and the quay — which is what makes it the
  // brawl the harbour's open water beside it is not.
  { kind: "parkade", x: -74, z: -72, params: { width: 32, depth: 22, floors: 3 } },
  { kind: "chapel", x: -108.75, z: 15.2 },
  // The Anchor, on the Strand, its door to the harbour across the road.
  { kind: "tavern", x: -110, z: -81.6 },
  { kind: "townhouse", x: -120.45, z: -58.5, rotY: Math.PI, params: { width: 7.1, depth: 6.8, enterable: true, litWindows: true } },
  { kind: "cottage", x: -111.74, z: -57.8, rotY: Math.PI, params: { width: 7.4, depth: 5.6, enterable: true, litWindows: true } },
  { kind: "townhouse", x: -121.1, z: -84.9, rotY: Math.PI / 2, params: { width: 6.2, depth: 6.6 } },
  { kind: "townhouse", x: -121.2, z: -76.95, rotY: Math.PI / 2, params: { width: 7, depth: 6.4 } },
  { kind: "townhouse", x: -121.2, z: -68.82, rotY: Math.PI / 2, params: { width: 6.6, depth: 6.4 } },
  { kind: "townhouse", x: -104.35, z: -71.7, rotY: -Math.PI / 2, params: { width: 6.6, depth: 6.5, enterable: true, litWindows: true } },
  { kind: "townhouse", x: -114.9, z: -41.6, params: { width: 6.2, depth: 6.6 } },
  { kind: "townhouse", x: -107.15, z: -41.65, params: { width: 6.8, depth: 6.5 } },
  { kind: "cottage", x: -112.4, z: -7.8, rotY: Math.PI, params: { width: 6.6, depth: 5.6 } },
  { kind: "townhouse", x: -104.08, z: -8.5, rotY: Math.PI, params: { width: 6.7, depth: 6.8 } },
  { kind: "townhouse", x: -113.25, z: -33.4, rotY: Math.PI / 2, params: { width: 6.7, depth: 6.3, litWindows: true } },
  { kind: "townhouse", x: -113.2, z: -24.43, rotY: Math.PI / 2, params: { width: 7.2, depth: 6.4, enterable: true, litWindows: true } },
  { kind: "townhouse", x: -113.15, z: -16.53, rotY: Math.PI / 2, params: { width: 6.1, depth: 6.5, litWindows: true } },
  { kind: "townhouse", x: -104.3, z: -33.6, rotY: -Math.PI / 2, params: { width: 6.3, depth: 6.4, enterable: true } },
  { kind: "townhouse", x: -104.35, z: -26.32, rotY: -Math.PI / 2, params: { width: 6, depth: 6.5, litWindows: true } },
  { kind: "cottage", x: -104.1, z: -18.52, rotY: -Math.PI / 2, params: { width: 6.6, depth: 6.2 } },
  { kind: "shophouse", x: -85.55, z: -37.4, rotY: Math.PI, params: { width: 12.3, depth: 15.6, floors: 2, tint: "#7c4a3f" } },
  { kind: "shophouse", x: -71.7, z: -37.4, rotY: Math.PI, params: { width: 12.4, depth: 15.6, floors: 2, tint: "#5c5340" } },
  { kind: "shophouse", x: -86.15, z: -12.6, params: { width: 11.3, depth: 15.6, floors: 3, tint: "#2f4a5c", sign: "#ff7a3c" } },
  { kind: "shophouse", x: -73.5, z: -12.7, params: { width: 11, depth: 15.8, floors: 2, tint: "#3f4b52", sign: "#7dff9e" } },
  { kind: "shophouse", x: -85.5, z: 12.6, rotY: Math.PI, params: { width: 12.4, depth: 15.6, floors: 2, tint: "#55603c", sign: "#7dff9e" } },
  { kind: "shophouse", x: -71.8, z: 12.6, rotY: Math.PI, params: { width: 12, depth: 15.6, floors: 2, tint: "#2f4a5c", sign: "#ff4f4f" } },
  { kind: "townhouse", x: -143.35, z: -86, rotY: -Math.PI / 2, params: { width: 7, depth: 6.7, enterable: true } },
  { kind: "cottage", x: -143.05, z: -77.17, rotY: -Math.PI / 2, params: { width: 7.6, depth: 6.3 } },
  { kind: "townhouse", x: -143.25, z: -67.83, rotY: -Math.PI / 2, params: { width: 7.2, depth: 6.5 } },
  { kind: "townhouse", x: -143.35, z: -59.52, rotY: -Math.PI / 2, params: { width: 6.4, depth: 6.7, enterable: true } },
  { kind: "townhouse", x: -143.35, z: -50.98, rotY: -Math.PI / 2, params: { width: 7.1, depth: 6.7, litWindows: true } },
  { kind: "townhouse", x: -143.3, z: -43.09, rotY: -Math.PI / 2, params: { width: 6, depth: 6.6, enterable: true } },
  { kind: "shophouse", x: -139.1, z: -11.85, rotY: Math.PI / 2, params: { width: 11.7, depth: 15.6, floors: 3, tint: "#2f4a5c", sign: "#39e0d0" } },
  { kind: "shophouse", x: -139.1, z: 1.2, rotY: Math.PI / 2, params: { width: 11.4, depth: 15.6, floors: 2, tint: "#6b4a2f" } },
  { kind: "shophouse", x: -139.15, z: 14.75, rotY: Math.PI / 2, params: { width: 12.7, depth: 15.7, floors: 2, tint: "#5c5340" } },
  { kind: "shophouse", x: -139.25, z: 29.5, rotY: Math.PI / 2, params: { width: 13.8, depth: 15.9, floors: 2, tint: "#2f4a5c" } },
  { kind: "shophouse", x: -147.1, z: 71, rotY: Math.PI / 2, params: { width: 13.4, depth: 15.6, floors: 2, tint: "#6b4a2f" } },
  { kind: "shophouse", x: -147.1, z: 85.25, rotY: Math.PI / 2, params: { width: 12.1, depth: 15.6, floors: 3, tint: "#4a5a4a", sign: "#ff7a3c" } },
  { kind: "shophouse", x: -147.1, z: 100.8, rotY: Math.PI / 2, params: { width: 10, depth: 15.6, floors: 2, tint: "#3f4b52", sign: "#ff5f7a" } },
  // ===== the Ness ==================================================================
  // The working end of the harbour, on the low ground between the Strand and
  // the pier: net lofts along the Strand Road, drying racks on the fish quay,
  // the boat shed at the pier root, and the boats drawn up on the shingle.
  { kind: "netLoft", x: -125.05, z: -106.95, rotY: Math.PI, params: { width: 9, depth: 7 } },
  { kind: "netLoft", x: -112.6, z: -106.95, rotY: Math.PI, params: { width: 9.1, depth: 7 } },
  { kind: "depot", x: -141, z: -122, rotY: Math.PI / 2, params: { width: 20, depth: 16, height: 7 } },
  { kind: "fishRack", x: -118, z: -114, params: { length: 9 } },
  { kind: "fishRack", x: -118, z: -120, params: { length: 9 } },
  { kind: "crates", x: -128, z: -114 },
  { kind: "crates", x: -111, z: -132 },
  { kind: "crates", x: -96, z: -138 },
  // ===== A: the Exchange ===========================================================
  // The Exchange, on its own square at the top of Fore Street: three walked
  // floors and a window band on three bearings over the High Town, with the
  // square in front of it and the garden behind. Every street into the High
  // Town climbs to it.
  { kind: "office", x: -90, z: 66, params: { width: 30, depth: 24, floors: 3, litWindows: true } },
  { kind: "tower", x: -117.6, z: 69.9, rotY: -Math.PI / 2, params: { width: 13, depth: 14, height: 23 } },
  { kind: "tower", x: -117.6, z: 85.7, rotY: -Math.PI / 2, params: { width: 13, depth: 14, height: 17 } },
  // ===== midtown ===================================================================
  // The commercial blocks between the square and High Street: the tall stock,
  // on the hill, so the skyline climbs away from the water. Every block is
  // lined on all four sides, the corners to the long streets.
  { kind: "tower", x: -38.1, z: 52.9, rotY: Math.PI, params: { width: 22, depth: 20, height: 31 } },
  { kind: "tower", x: -16.1, z: 52.4, rotY: Math.PI, params: { width: 18, depth: 19, height: 27 } },
  { kind: "tower", x: -36.6, z: 90.6, params: { width: 21, depth: 22, height: 44 } },
  { kind: "shophouse", x: -43.85, z: 69.8, rotY: -Math.PI / 2, params: { width: 11.1, depth: 15.7, floors: 2, tint: "#4a5a4a", sign: "#ff5f7a" } },
  { kind: "shophouse", x: -14.1, z: 71.25, rotY: Math.PI / 2, params: { width: 13.8, depth: 15.6, floors: 2, tint: "#7c4a3f", sign: "#c46cff" } },
  { kind: "tower", x: 14.4, z: 51.4, rotY: Math.PI, params: { width: 17, depth: 17, height: 36 } },
  { kind: "shophouse", x: 32.55, z: 50.8, rotY: Math.PI, params: { width: 11.5, depth: 16, floors: 3, tint: "#7c4a3f" } },
  { kind: "tower", x: 16.4, z: 92.1, params: { width: 19, depth: 19, height: 22 } },
  { kind: "tower", x: 13.95, z: 68.15, rotY: -Math.PI / 2, params: { width: 13.4, depth: 15.1, height: 15 } },
  { kind: "tower", x: 32.05, z: 67.25, rotY: Math.PI / 2, params: { width: 11.6, depth: 15.1, height: 10 } },
  // ===== D: the Terminal ===========================================================
  // The railway terminus at the top of the docks: the train shed with its
  // arches to the forecourt, the taxi rank, and no interior to the flag at all.
  // The fast flag, and the open one.
  { kind: "depot", x: 83, z: 84, rotY: Math.PI, params: { width: 44, depth: 20, height: 9, litWindows: true } },
  { kind: "tower", x: 106.6, z: 52.8, rotY: Math.PI / 2, params: { width: 12.8, depth: 12, height: 9 } },
  { kind: "planter", x: 60, z: 66, params: { width: 2.6, depth: 1.4 } },
  { kind: "planter", x: 86, z: 52, params: { width: 2.6, depth: 1.4 } },
  { kind: "planter", x: 96, z: 64, rotY: Math.PI / 2, params: { width: 2.6, depth: 1.4 } },
  { kind: "barrier", x: 78, z: 47, rotY: Math.PI / 2, params: { length: 9 } },
  { kind: "car", x: 64, z: 50, params: { tint: "#2f3338" } },
  { kind: "car", x: 70, z: 50, params: { tint: "#2f5f9c" } },
  { kind: "streetLight", x: 56, z: 70, params: { height: 7.5, lit: true } },
  { kind: "streetLight", x: 98, z: 50, rotY: Math.PI, params: { height: 7.5, lit: true } },
  // ===== the east town =============================================================
  { kind: "shophouse", x: 59.3, z: 6.1, rotY: Math.PI, params: { width: 13, depth: 15.6, floors: 2, tint: "#55603c", sign: "#4fd6ff" } },
  { kind: "tower", x: 75.4, z: 6.4, rotY: Math.PI, params: { width: 16, depth: 16, height: 23 } },
  { kind: "shophouse", x: 91.4, z: 6.1, rotY: Math.PI, params: { width: 12.6, depth: 15.6, floors: 3, tint: "#55603c" } },
  { kind: "shophouse", x: 62.6, z: 25.9, params: { width: 13.8, depth: 15.6, floors: 3, tint: "#4a5a4a", sign: "#ff7a3c" } },
  { kind: "shophouse", x: 77.5, z: 25.9, params: { width: 13, depth: 15.6, floors: 2, tint: "#6a3a3a" } },
  { kind: "tower", x: 94.7, z: 25.6, params: { width: 18, depth: 16, height: 13 } },
  // ===== E: the Harbour Board ======================================================
  // The Harbour Board's offices at the head of the docks: three walked floors
  // over its plaza on Rope Street, its yard on Warehouse Lane and the quay. The
  // flag is in the building; the plaza in front of it is the open ground an
  // attacker from the town has to cross.
  { kind: "office", x: 82, z: -45, params: { width: 28, depth: 24, floors: 3, litWindows: true } },
  { kind: "planter", x: 60, z: -26, params: { width: 2.6, depth: 1.4 } },
  { kind: "planter", x: 74, z: -20, rotY: Math.PI / 2, params: { width: 2.6, depth: 1.4 } },
  { kind: "planter", x: 88, z: -27, params: { width: 2.6, depth: 1.4 } },
  { kind: "planter", x: 66, z: -16, params: { width: 2.6, depth: 1.4 } },
  { kind: "barrier", x: 81, z: -18, rotY: Math.PI / 2, params: { length: 6 } },
  { kind: "tower", x: 99.6, z: -26.4, rotY: Math.PI / 2, params: { width: 10.4, depth: 10, height: 14 } },
  { kind: "tower", x: 58.5, z: -46.6, rotY: -Math.PI / 2, params: { width: 22, depth: 11, height: 14 } },
  // ===== the docks =================================================================
  // Warehouses on the Dock Road, their loading bays to the cranes.
  { kind: "depot", x: 67, z: -98, rotY: Math.PI, params: { width: 28, depth: 16, litWindows: true } },
  { kind: "depot", x: 99, z: -98, rotY: Math.PI, params: { width: 26, depth: 16 } },
  { kind: "crane", x: 76, z: -146 },
  { kind: "crane", x: 108, z: -146 },
  { kind: "crates", x: 62, z: -132 },
  { kind: "crates", x: 88, z: -128, rotY: Math.PI / 2 },
  { kind: "crates", x: 94, z: -142 },
  { kind: "crates", x: 122, z: -132, rotY: Math.PI / 2 },
  { kind: "crates", x: 57, z: -142, rotY: -Math.PI / 2 },
  { kind: "depot", x: 135.3, z: -95.3, rotY: -Math.PI / 2, params: { width: 22, depth: 16 } },
  { kind: "depot", x: 135.3, z: -67, rotY: -Math.PI / 2, params: { width: 22, depth: 16 } },
  { kind: "tower", x: 128.4, z: 2.9, rotY: -Math.PI / 2, params: { width: 17, depth: 18, height: 18 } },
  { kind: "tower", x: 136.4, z: 52.9, rotY: -Math.PI / 2, params: { width: 19, depth: 18, height: 27 } },
  { kind: "tower", x: 136.4, z: 75.2, rotY: -Math.PI / 2, params: { width: 18, depth: 18, height: 28 } },
  // ===== the ridge =================================================================
  // High Street's north side, the tallest stock on the highest ground.
  { kind: "tower", x: -113.6, z: 117.9, rotY: Math.PI, params: { width: 20, depth: 23, height: 28 } },
  { kind: "tower", x: -88.8, z: 115.4, rotY: Math.PI, params: { width: 22, depth: 18, height: 18 } },
  { kind: "tower", x: -33.6, z: 126.4, rotY: Math.PI, params: { width: 24, depth: 24, height: 23 } },
  { kind: "tower", x: -6.8, z: 126.9, rotY: Math.PI, params: { width: 22, depth: 25, height: 39 } },
  { kind: "tower", x: 19.5, z: 126.4, rotY: Math.PI, params: { width: 23, depth: 24, height: 24 } },
  { kind: "tower", x: 60.4, z: 118.4, rotY: Math.PI, params: { width: 20, depth: 24, height: 19 } },
  { kind: "tower", x: 84.2, z: 118.9, rotY: Math.PI, params: { width: 20, depth: 25, height: 18 } },
  { kind: "tower", x: 137.4, z: 114.9, rotY: -Math.PI / 2, params: { width: 17, depth: 20, height: 22 } },
  // ===== the street, as furnished ==================================================
  // **Every column carries a LENS and only the ones marked `lit` carry a
  // LIGHT** — the sixteen-slot budget made concrete, not a statement about
  // which lamps are on. The lit ones are where a body stands at a flag: the
  // square's four, the forecourt's two, and one each at A, B and E. Each
  // stands on the kerb with its arm out over the carriageway.
  { kind: "streetLight", x: -63.2, z: 52, params: { height: 7.5, lit: true } },
  { kind: "streetLight", x: -56.4, z: -86, params: { height: 7.5, lit: true } },
  { kind: "streetLight", x: 78, z: -13.2, rotY: -Math.PI / 2, params: { height: 7.5, lit: true } },
  { kind: "streetLight", x: -43.6, z: -86, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: -43.6, z: -62, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: -43.6, z: -40, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: -30, z: -34, rotY: -Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: -6, z: -34, rotY: -Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: 18, z: -34, rotY: -Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: 39.4, z: -40, params: { height: 7.5 } },
  { kind: "streetLight", x: 39.4, z: -66, params: { height: 7.5 } },
  { kind: "streetLight", x: 39.4, z: -92, params: { height: 7.5 } },
  { kind: "streetLight", x: 66, z: -122.4, rotY: -Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: 96, z: -122.4, rotY: -Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: -118, z: -90.6, rotY: Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: -80, z: -90.6, rotY: Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: -44.6, z: -4, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: -44.6, z: 22, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: -52.6, z: 62, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: -52.6, z: 86, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: 5.4, z: 78, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: 51.4, z: 6, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: 51.4, z: 60, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: 51.4, z: 92, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: -100, z: 104.6, rotY: Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: -78, z: 104.6, rotY: Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: -20, z: 112.6, rotY: Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: 16, z: 112.6, rotY: Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: 70, z: 104.6, rotY: Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: 100, z: 104.6, rotY: Math.PI / 2, params: { height: 7.5 } },
  { kind: "streetLight", x: 126.1, z: -90, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: 126.1, z: -60, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: 118.1, z: 0, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: 126.1, z: 60, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: 126.1, z: 96, rotY: Math.PI, params: { height: 7.5 } },
  { kind: "streetLight", x: -138.1, z: -80, params: { height: 7.5 } },
  { kind: "streetLight", x: -138.1, z: -50, params: { height: 7.5 } },
  { kind: "streetLight", x: -130.1, z: 10, params: { height: 7.5 } },
  { kind: "streetLight", x: -138.1, z: 80, params: { height: 7.5 } },
  { kind: "streetLight", x: -138.1, z: 110, params: { height: 7.5 } },
  // Parked cars, nose along the kerb: one side of a through road only, so a hull still has the other.
  { kind: "car", x: -30.8, z: -21.6, rotY: Math.PI, params: { tint: "#2f3338" } },
  { kind: "car", x: -24.6, z: -21.6, params: { tint: "#2f5f9c" } },
  { kind: "car", x: -18.4, z: -21.6, rotY: Math.PI, params: { tint: "#3f7d5a" } },
  { kind: "car", x: 6.4, z: -21.6, params: { tint: "#d8d4c8" } },
  { kind: "car", x: 18.8, z: -21.6, rotY: Math.PI, params: { tint: "#b8a63c" } },
  { kind: "car", x: -53.4, z: -13, rotY: Math.PI / 2, params: { tint: "#b8a63c" } },
  { kind: "car", x: -53.4, z: -6.8, rotY: -Math.PI / 2, params: { tint: "#2f3338" } },
  { kind: "car", x: -53.4, z: 5.6, rotY: -Math.PI / 2, params: { tint: "#a8352e" } },
  { kind: "car", x: -53.4, z: 18, rotY: -Math.PI / 2, params: { tint: "#3f4b52" } },
  { kind: "car", x: 42.6, z: -13, rotY: -Math.PI / 2, params: { tint: "#b8a63c" } },
  { kind: "car", x: 42.6, z: 5.6, rotY: Math.PI / 2, params: { tint: "#6b463a" } },
  { kind: "car", x: 42.6, z: 73.8, rotY: Math.PI / 2, params: { tint: "#3f7d5a" } },
  { kind: "car", x: 42.6, z: 80, rotY: -Math.PI / 2, params: { tint: "#5c5340" } },
  { kind: "car", x: 42.6, z: 86.2, rotY: -Math.PI / 2, params: { tint: "#b8a63c" } },
  { kind: "car", x: -3.4, z: 33, rotY: Math.PI / 2, params: { tint: "#d8d4c8" } },
  { kind: "car", x: -3.4, z: 45.4, rotY: Math.PI / 2, params: { tint: "#b8a63c" } },
  { kind: "car", x: -3.4, z: 51.6, rotY: Math.PI / 2, params: { tint: "#5c5340" } },
  { kind: "car", x: -3.4, z: 70.2, rotY: -Math.PI / 2, params: { tint: "#c2762a" } },
  { kind: "car", x: -3.4, z: 82.6, rotY: Math.PI / 2, params: { tint: "#2f3338" } },
  { kind: "car", x: -3.4, z: 88.8, rotY: Math.PI / 2, params: { tint: "#2f5f9c" } },
  { kind: "car", x: -41, z: 30.6, params: { tint: "#3f7d5a" } },
  { kind: "car", x: -34.8, z: 30.6, params: { tint: "#3f4b52" } },
  { kind: "car", x: -22.4, z: 30.6, rotY: Math.PI, params: { tint: "#a8352e" } },
  { kind: "car", x: 8.6, z: 30.6, params: { tint: "#6b463a" } },
  { kind: "car", x: 27.2, z: 30.6, params: { tint: "#2f5f9c" } },
  { kind: "car", x: -41, z: 104.6, rotY: Math.PI, params: { tint: "#a8352e" } },
  { kind: "car", x: -34.8, z: 104.6, rotY: Math.PI, params: { tint: "#4a4f45" } },
  { kind: "car", x: -22.4, z: 104.6, rotY: Math.PI, params: { tint: "#a8352e" } },
  { kind: "car", x: -3.8, z: 104.6, params: { tint: "#c2762a" } },
  { kind: "car", x: 124.4, z: -101, rotY: Math.PI / 2, params: { tint: "#2f5f9c" } },
  { kind: "car", x: 124.4, z: -94.8, rotY: Math.PI / 2, params: { tint: "#2f5f9c" } },
  { kind: "car", x: 124.4, z: -82.4, rotY: -Math.PI / 2, params: { tint: "#d8d4c8" } },
  { kind: "car", x: 124.4, z: -76.2, rotY: Math.PI / 2, params: { tint: "#2f3338" } },
  { kind: "car", x: 124.4, z: -63.8, rotY: Math.PI / 2, params: { tint: "#5c5340" } },
  { kind: "car", x: 124.4, z: 61.4, rotY: -Math.PI / 2, params: { tint: "#8d3f7a" } },
  { kind: "car", x: 124.4, z: 67.6, rotY: -Math.PI / 2, params: { tint: "#a8352e" } },
  { kind: "car", x: 124.4, z: 73.8, rotY: -Math.PI / 2, params: { tint: "#2f3338" } },
  { kind: "car", x: -127.6, z: 69, rotY: Math.PI / 2, params: { tint: "#8d3f7a" } },
  { kind: "car", x: -127.6, z: 81.4, rotY: -Math.PI / 2, params: { tint: "#d8d4c8" } },
  { kind: "car", x: -127.6, z: 87.6, rotY: Math.PI / 2, params: { tint: "#3f7d5a" } },
  { kind: "car", x: 81.8, z: -4.6, rotY: Math.PI, params: { tint: "#a8352e" } },
  { kind: "car", x: 94.2, z: -4.6, params: { tint: "#3f4b52" } },
  { kind: "car", x: 57, z: -76.6, rotY: Math.PI, params: { tint: "#2f3338" } },
  { kind: "car", x: 63.2, z: -76.6, params: { tint: "#3f4b52" } },
  { kind: "car", x: 69.4, z: -76.6, rotY: Math.PI, params: { tint: "#b8a63c" } },
  { kind: "car", x: 81.8, z: -76.6, params: { tint: "#2f3338" } },
  { kind: "car", x: 94.2, z: -76.6, rotY: Math.PI, params: { tint: "#5c5340" } },
  { kind: "car", x: 106.6, z: -76.6, rotY: Math.PI, params: { tint: "#8d3f7a" } },
  { kind: "car", x: -108.8, z: 43.4, rotY: Math.PI, params: { tint: "#2f5f9c" } },
  { kind: "car", x: -102.6, z: 43.4, params: { tint: "#4a4f45" } },
  { kind: "car", x: -96.4, z: 43.4, params: { tint: "#4a4f45" } },
  { kind: "car", x: -71.6, z: 43.4, params: { tint: "#8d3f7a" } },
  { kind: "car", x: 63.2, z: 36.6, rotY: Math.PI, params: { tint: "#c2762a" } },
  { kind: "car", x: 81.8, z: 36.6, rotY: Math.PI, params: { tint: "#8d3f7a" } },
  { kind: "car", x: -110.6, z: -92.6, rotY: Math.PI, params: { tint: "#8d3f7a" } },
  // The fish market on the head quay, its counters to the road.
  { kind: "stall", x: -18, z: -33.6, rotY: Math.PI },
  { kind: "stall", x: 10, z: -33.6, rotY: Math.PI },
  { kind: "crates", x: -42.4, z: -50, rotY: Math.PI / 2 },
  { kind: "crates", x: -42.6, z: -76, rotY: Math.PI / 2 },
  { kind: "crates", x: 38.6, z: -58, rotY: Math.PI / 2 },
  { kind: "crates", x: 38.4, z: -100, rotY: Math.PI / 2 },
  { kind: "crates", x: -4, z: -33.4, rotY: Math.PI / 2 },
];

/**
 * The town's dressing, the harbour's working clutter and the country beyond
 * the play square. What blocks is cover and is on the bill for every ray;
 * what does not is dressing and costs nothing but the merge. Every region is
 * checked against the finished floor and the claims by the generator.
 *
 * ADDING A PLACEMENT REROLLS ALL OF THIS — `findSpot` draws from the shared
 * stream once per attempt, and placements build before scatter.
 */
const scatter: ScatterSpec[] = [
  // ===== the square's trees ========================================================
  // One stand per quarter of the lawn, clear of the paths and the memorial —
  // the only cover on C that is not furniture, and the reason the square is
  // crossable at all. Ash, not the pines the business district planted:
  // this is a harbour town's municipal square.
  { prop: "ashTree", x: 13.5, z: 15.5, width: 15, depth: 15, count: 4, scale: [0.85, 1.15], blocking: true, clearance: 4 },
  { prop: "ashTree", x: -13.5, z: 15.5, width: 15, depth: 15, count: 4, scale: [0.85, 1.15], blocking: true, clearance: 4 },
  { prop: "ashTree", x: -14.5, z: -11.5, width: 14, depth: 9, count: 4, scale: [0.85, 1.15], blocking: true, clearance: 4 },
  { prop: "ashTree", x: 14.5, z: -11.5, width: 14, depth: 9, count: 4, scale: [0.85, 1.15], blocking: true, clearance: 4 },
  // ===== the gardens and the churchyard ============================================
  { prop: "ashTree", x: -84, z: 87, width: 34, depth: 12, count: 7, scale: [0.85, 1.15], blocking: true, clearance: 4 },
  { prop: "ashTree", x: 73, z: -24, width: 34, depth: 10, count: 4, scale: [0.85, 1.15], blocking: true, clearance: 4 },
  { prop: "ashTree", x: -152, z: -104, width: 8, depth: 6, count: 2, scale: [0.85, 1.15], blocking: true, clearance: 4 },
  { prop: "gravestone", x: -108.8, z: 34, width: 12, depth: 2, count: 6, scale: [0.8, 1.2], blocking: true, clearance: 0.7 },
  // ===== the working waterfront ====================================================
  // Barrels on the quaysides and pallets on the dock apron: what a working
  // harbour leaves lying about, and what a body crossing one ducks behind.
  { prop: "barrel", x: -42.2, z: -66, width: 3, depth: 20, count: 4, scale: [0.9, 1.1], blocking: true, clearance: 0.6 },
  { prop: "barrel", x: 36, z: -82, width: 3, depth: 20, count: 4, scale: [0.9, 1.1], blocking: true, clearance: 0.6 },
  { prop: "barrel", x: -116, z: -128, width: 10, depth: 6, count: 5, scale: [0.9, 1.1], blocking: true, clearance: 0.6 },
  { prop: "palletStack", x: 92, z: -134, width: 10, depth: 6, count: 4, scale: [0.9, 1.2], blocking: true, clearance: 1.6 },
  { prop: "barrel", x: 64, z: -138, width: 10, depth: 8, count: 6, scale: [0.9, 1.1], blocking: true, clearance: 0.6 },
  { prop: "palletStack", x: 118, z: -142, width: 10, depth: 10, count: 4, scale: [0.9, 1.2], blocking: true, clearance: 1.6 },
  { prop: "palletStack", x: 140, z: -114, width: 12, depth: 8, count: 3, scale: [0.9, 1.2], blocking: true, clearance: 1.6 },
  { prop: "barrel", x: 70, z: -86.5, width: 26, depth: 2.5, count: 4, scale: [0.9, 1.1], blocking: true, clearance: 0.6 },
  // ===== the back closes ===========================================================
  // Skips and bins behind the rows, where a town actually accumulates.
  { prop: "binPair", x: -73.8, z: -25.1, width: 36.5, depth: 6.1, count: 4, scale: [0.9, 1.15], blocking: true, clearance: 1.4 },
  { prop: "skip", x: -73.8, z: -25.1, width: 36.5, depth: 6.1, count: 1, scale: [0.9, 1.1], blocking: true, clearance: 2.4 },
  { prop: "binPair", x: -29, z: 71.3, width: 11.2, depth: 13.2, count: 2, scale: [0.9, 1.15], blocking: true, clearance: 1.4 },
  { prop: "skip", x: -29, z: 71.3, width: 11.2, depth: 13.2, count: 1, scale: [0.9, 1.1], blocking: true, clearance: 2.4 },
  // ===== litter ====================================================================
  // Banked against the kerbs and blown into the corners: no collider, no nav
  // cost and nothing to any ray, laid straight over the flags where it falls.
  { prop: "litter", x: -50, z: -60, width: 12, depth: 60, count: 12, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: -2, z: -26, width: 80, depth: 10, count: 14, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: 46, z: -70, width: 12, depth: 80, count: 12, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: -50, z: 4, width: 10, depth: 56, count: 8, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: 0, z: 66, width: 10, depth: 70, count: 8, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: 46, z: 66, width: 10, depth: 70, count: 8, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: 80, z: -116, width: 70, depth: 10, count: 8, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: -90, z: -96, width: 80, depth: 9, count: 10, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: 0, z: 4, width: 44, depth: 40, count: 10, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: 80, z: 40, width: 60, depth: 9, count: 6, scale: [0.8, 1.3], clearance: 3.5 },
  { prop: "litter", x: -90, z: 40, width: 60, depth: 9, count: 6, scale: [0.8, 1.3], clearance: 3.5 },
  // ===== THE COUNTRY OUTSIDE THE TOWN ========================================
  // Appended LAST, and the order is mechanical: every region draws from one
  // seeded stream in array order, so a region spliced in above re-rolls every
  // one below it.
  //
  // **This is the borderland, and it is here because a flat margin reads as a
  // backdrop rather than as distance** — Harrowmead's finding. The hills are
  // the horizon, but a `downs` face is ONE unbroken surface a hundred metres
  // tall, and the 180 m of plain in front of it is another; trees sown in
  // front of a slope are what give the slope a scale.
  //
  // **None of it BLOCKS, and that is a rule rather than a saving.** Out here a
  // collider would be geometry outside the nav grid that the bots can neither
  // see nor route around, and something to catch a player sprinting home
  // against the leash's countdown. Non-blocking scatter emits no collider and
  // no `WorldBox`, so the baked collision set is unchanged by every tree here.
  //
  // **It is not a RING**, for Greyfen's reason: a continuous belt round a town
  // is a town in a clearing. Each side gets two or three stands with open
  // ground between them, starting about forty metres past the play square.
  // The southern quadrant gets none at all: it is the sea.
  { prop: "pine", x: -232, z: 268, width: 150, depth: 96, count: 80, scale: [0.9, 1.4], clearance: 1.2 },
  { prop: "pine", x: -40, z: 292, width: 170, depth: 84, count: 70, scale: [0.9, 1.4], clearance: 1.2 },
  { prop: "pine", x: 196, z: 276, width: 190, depth: 104, count: 95, scale: [0.9, 1.4], clearance: 1.2 },
  { prop: "pine", x: -288, z: 96, width: 92, depth: 210, count: 85, scale: [0.9, 1.4], clearance: 1.2 },
  { prop: "pine", x: -274, z: -86, width: 110, depth: 106, count: 55, scale: [0.9, 1.4], clearance: 1.2 },
  { prop: "pine", x: 286, z: 30, width: 96, depth: 250, count: 100, scale: [0.9, 1.4], clearance: 1.2 },
  { prop: "pine", x: 268, z: -94, width: 120, depth: 92, count: 50, scale: [0.9, 1.4], clearance: 1.2 },
  { prop: "pine", x: 96, z: 236, radius: 24, count: 15, scale: [0.85, 1.25], clearance: 1.2 },
  { prop: "pine", x: -150, z: 228, radius: 20, count: 11, scale: [0.85, 1.25], clearance: 1.2 },
  // Broadleaf on the near ground, where the town's own gardens run out into
  // the country: the same ash the square is planted with.
  { prop: "ashTree", x: -226, z: -20, radius: 30, count: 12, scale: [0.9, 1.3], clearance: 3 },
  { prop: "ashTree", x: 214, z: 150, radius: 32, count: 12, scale: [0.9, 1.3], clearance: 3 },
  { prop: "ashTree", x: -214, z: 176, radius: 26, count: 9, scale: [0.9, 1.3], clearance: 3 },
];

/**
 * The five objectives. A, B and E stand INSIDE a building at ground-floor
 * height and the capture zone is a cylinder, so every storey above the flag
 * is inside the zone too; each is at its building's centre, which every one of
 * those builders leaves clear of its core, its stair lanes and its columns. C
 * stands ON the memorial's top tier, 3.5 m out from the shaft, because a flag
 * at the exact centre would be inside it. `pos.y` is the walked height.
 */
const controlPoints: ControlPointDef[] = [
  { id: "A", name: "Alpha", pos: new Vector3(-90, 3.2, 66), radius: 15 },
  { id: "B", name: "Bravo", pos: new Vector3(-74, 0.5, -72), radius: 14 },
  { id: "C", name: "Charlie", pos: new Vector3(2.5, 1.62, 2.5), radius: 16 },
  { id: "D", name: "Delta", pos: new Vector3(72, 2, 58), radius: 14 },
  { id: "E", name: "Echo", pos: new Vector3(82, 0.2, -45), radius: 15 },
];

/**
 * Home spawns in the two corner yards, and one spawn per objective outside
 * its ring on the side that faces the fight it feeds — each on the bearing the
 * old map's had from its flag. C's is on the perpendicular bisector of the two
 * homes, so the flag every round turns on is the same walk back from both.
 */
const spawns: SpawnPointDef[] = [
  { team: 0, pos: new Vector3(-145, 4, 134), yaw: (Math.PI * 3) / 4 },
  { team: 0, pos: new Vector3(-137, 3.98, 142), yaw: (Math.PI * 3) / 4 },
  { team: 0, pos: new Vector3(-152, 4, 126), yaw: (Math.PI * 3) / 4 },
  { team: 1, pos: new Vector3(144, 0, -140), yaw: -Math.PI / 4 },
  { team: 1, pos: new Vector3(136, 0, -146), yaw: -Math.PI / 4 },
  { team: 1, pos: new Vector3(152, 0, -132), yaw: -Math.PI / 4 },
  { team: null, controlPoint: "A", pos: new Vector3(-80, 2.46, 46), yaw: 0 },
  { team: null, controlPoint: "B", pos: new Vector3(-74, 0.3, -50), yaw: Math.PI },
  { team: null, controlPoint: "C", pos: new Vector3(16, 0.6, 17.9), yaw: (-Math.PI * 3) / 4 },
  { team: null, controlPoint: "D", pos: new Vector3(60, 1.44, 41), yaw: 0.54 },
  { team: null, controlPoint: "E", pos: new Vector3(82, 0.01, -23), yaw: Math.PI },
];

/**
 * One hardstanding per side, in the yard that side deploys into, clear of the
 * infantry spawns and headed for its own home road: the Valeguard's down the
 * West Road from the Heights, the Redline's up the Station Road from the goods
 * yard. **Two, and exactly two** — the respawn is per hardstanding, so the
 * number of entries IS how many tanks a side can field.
 */
const vehicles: VehicleSpawnDef[] = [
  { team: 0, pos: new Vector3(-150, 4, 114), yaw: Math.PI / 2 },
  { team: 1, pos: new Vector3(138, 0, -126), yaw: -Math.PI / 4 },
];

/**
 * THE WATER, as seven rectangles at one surface. `y` is -2.2 on all of them
 * and they must go on agreeing, for the drawing and for the sound:
 * `MapBuilder.waterAmbience` joins rects into one BODY when they touch and
 * agree, and one harbour shelved into seven seas would be seven emitters.
 *
 * **A rect's bed map is 512 texels a side however big it is**, so the harbour
 * is its own rect and is no wider than the play square; the open sea is laid
 * round it, its far edges past `fogEnd` from anywhere a living player can
 * stand, and its seams on the play edge at the foot of the quays' outer faces.
 */
const water: WaterRect[] = [
  // The harbour: the play square's own water, from the head quay to the play
  // edge and across the whole width, so it also carries the strip of sea
  // under the pier's and the docks' outer faces. ONE rect, so its probe
  // stands in the harbour rather than out at sea, and its bed map is spent
  // on the only shoreline anybody walks along.
  { x: 0, z: -99, width: 320, depth: 122, y: -2.2 },
  // The frontage: the open sea south of the play square out past both
  // headlands, and the two strips that close it against the coast either
  // side of the square. Seams stand on the play edge, along the foot of the
  // quays' outer faces, except across the harbour mouth.
  { x: 0, z: -430, width: 1400, depth: 540, y: -2.2 },
  { x: -430, z: -150, width: 540, depth: 20, y: -2.2 },
  { x: 430, z: -150, width: 540, depth: 20, y: -2.2 },
  // The western and eastern seas, and the ocean that is the southern horizon.
  { x: -1700, z: -420, width: 2000, depth: 560, y: -2.2 },
  { x: 1700, z: -420, width: 2000, depth: 560, y: -2.2 },
  { x: 0, z: -1700, width: 5400, depth: 2000, y: -2.2 },
];

/**
 * The lawns: the civic square's four quarters, the Exchange's garden, the
 * churchyard and the rough ground of the Ness. Purely visual — no collider, no
 * nav cost — and a tuft that lands inside a collider is dropped at build time.
 */
const grass: GrassRect[] = [
  // The square's lawn, one rect per quarter, mown and cut clean at the kerbs and the paths.
  { x: 13, z: 15, width: 18, depth: 18, height: 0.75, edge: 0 },
  { x: -13, z: 15, width: 18, depth: 18, height: 0.75, edge: 0 },
  { x: -13, z: -11, width: 18, depth: 10, height: 0.75, edge: 0 },
  { x: 13, z: -11, width: 18, depth: 10, height: 0.75, edge: 0 },
  // The Exchange's garden.
  { x: -84, z: 87, width: 38, depth: 14, height: 0.7, edge: 0 },
  // The churchyard behind the Mariners' Church.
  { x: -108.8, z: 33, width: 14, depth: 4, height: 0.6, edge: 0 },
  // The rough ground of the Ness, round the boat shed.
  { x: -146, z: -116, width: 26, depth: 30, density: 0.7, height: 1.1 },
];

export const ColdharbourLayout: MapLayout = {
  placements,
  scatter,
  controlPoints,
  spawns,
  vehicles,
  water,
  grass,
  /**
   * Not `CONFIG.map.size`. Everything downstream takes the extent as an
   * argument; what a larger map owes is stated on `MapLayout.size`, and the
   * one that bites is that `terrain.size * terrain.cell` must equal this —
   * 80 x 4.
   */
  size: 320,
  /**
   * Three floors, a roof, a spandrel at every window and a wall head under
   * every ceiling stack six or seven candidates into one perimeter cell, and
   * `NavGrid` DROPS the overflow rather than sorting it in. The city kit's
   * builders emit their walked surfaces FIRST, so at the default 3 the floors
   * fill the slots and it is the spandrels and the roof that are dropped —
   * measured on this map before the re-lay, every storey of every enterable
   * building was reachable at 3, 4 and 5. Four is one slot of margin over a
   * value that already works, bought because the guarantee rests on emission
   * order inside a builder and the failure is a storey quietly missing from
   * the graph.
   */
  surfaces: 4,
  /**
   * Twice the default, for the `borderland` below: with 180 m of ground on
   * every side the default 48 cuts the floor into 61 patches, every one walked
   * by the frame at every distance because the floor carries no
   * `metadata.block`. At 96 it is 24.
   */
  terrainBlock: 96,
  /**
   * No wall and no rim: the ground carries on for 180 m past the play square
   * on every side and what stops a player leaving is the leash. **The margin
   * is the LANDFORM's here** — this map draws hills on three sides (see
   * `ridge`), and at 300 m the fog ate them; 180 puts their crest 330 m from
   * the nearest street at 93 m high. The roll is low because a third of the
   * borderland is SEABED, and at the default the bed's high points would come
   * up into the shallows and show a shoal through the open sea. `ease` is 30
   * because the leash's 69 m is the shorter of the two tests.
   */
  borderland: { margin: 180, roll: 1.8, ease: 30 },
  /**
   * **HILLS on three sides and the OPEN SEA on the fourth.** `downs` with
   * rolling summits and woods on them, and a `mouth` across the whole
   * southern side and both southern corners — `form: "none"` asked of one
   * arc, allowed because there IS something out there past `fogEnd`: the sea.
   * The mouth's width is arithmetic (the southern side, 680 m, plus a quarter
   * circle of crest at each corner: 680 + 2 x 150 x pi / 2 = 1151), and its
   * `ease` is what a headland IS — over 300 m of the crest's curve each range
   * grows out of the sea at its corner, so the bay the town stands on is held
   * between two headlands.
   */
  ridge: {
    form: "downs",
    slope: 0.19,
    slopeVariance: 0.06,
    mouth: [{ x: 0, z: -340, width: 1151, ease: 300 }],
    rolling: {
      relief: 0.3,
      summits: 16,
      knolls: 0.14,
      knollSize: 110,
      woods: 0.6,
      shore: 0.5,
    },
    seed: 0x43484252,
  },
  // Fixed so the dressing — and the colliders blocking scatter emits, and so
  // the nav graph — is identical on every boot.
  seed: 0x434f4c44,
};
