/**
 * check-proving.mjs — proves the proving ground did not ship.
 *
 * Runs at the END of `npm run build`, because it reads what a build EMITTED.
 * Everything else in that chain is a gate in front of the build; this one can
 * only be a gate behind it, and that is fine — the build it inspects is the
 * artefact, and a non-zero exit is what stops it being published.
 *
 * **It checks both artefact directories, and the second one is why it exists
 * as a script rather than as a habit.** `dist/` is what a player downloads and
 * `dist-server/` is what a match server runs, and the two builds shake
 * differently: Vite sets `moduleSideEffects: "no-external"` for the client and
 * leaves Rollup's default for SSR, so the server build kept the layout's
 * control points until `vite.server.config.ts` was told otherwise. Whichever
 * of the two exists is scanned; neither existing is the only thing that is an
 * error, because a gate that passes on an empty directory is not a gate.
 *
 * **`dist-server-dev/` is deliberately NOT scanned.** That is the dev-mode
 * server build `npm run simulate:dev` runs the proving ground out of
 * (`ENGINE_UPGRADE.md` S9), so it is the one artefact directory in the tree
 * where this map is supposed to be — it is gitignored, it is never deployed,
 * and scanning it would fail the build for the thing working.
 *
 * **What it is defending is a 400 kB map that is not a level.**
 * `src/world/proving/` is generated by `scripts/generate-proving-ground.mjs`
 * for `ENGINE_UPGRADE.md` S0, is registered in `src/world/maps.ts` behind
 * `import.meta.env.DEV`, and reaches the player through nothing. It stays out
 * of the bundle because Vite folds that flag to `false` and Rollup then shakes
 * the two generated modules away — which is a property of the way `MAPS` is
 * written, not a promise the build makes. Rewrite that ternary as a `push`, a
 * `filter`, or a `const dev = import.meta.env.DEV` one line up, and the shake
 * silently stops working while everything still compiles and runs.
 *
 * So this greps the emitted bundle for four strings that exist ONLY on the far
 * side of that gate, and fails on any of them:
 *
 *   - `Proving Ground`, the `MapDef.name` in `maps.ts` — present if the ternary
 *     was not folded at all;
 *   - `PG-Alpha`, a generated control point's name — present if the def was
 *     dropped but the layout module was still reached from somewhere else;
 *   - `PG-Level`, an export of `proving/heights.ts` that exists only to be
 *     found here — present if the HEIGHTFIELD was reached on its own;
 *   - `PG-Boxes`, the same device on `proving/collision.ts` — the 473 kB
 *     collider bake `ENGINE_UPGRADE.md` S9 needs in order to run the
 *     AUTHORITY on this map at all, and the largest of the four things here
 *     that must not ship. It is the fourth sentinel the note below predicted
 *     would be worth adding, and it was: nothing else in that file is a
 *     string, so it is a chunk of six thousand numbers that no other
 *     sentinel could see.
 *
 * **The third one is what ENGINE_UPGRADE.md S7 owed this file, and it is the
 * case its old note predicted.** The heightfield used to hang off the layout,
 * so `PG-Alpha` covered it: one module reached the other and shaking the first
 * took the second. `MapDef.heights` made it a lazy `import()` — a chunk ROOT,
 * which Rollup emits unless the arrow naming it is itself shaken away with
 * `PROVING`. It is, today. That is a property of how `maps.ts` is written and
 * not a promise the build makes, which is the entire premise of this script.
 *
 * Strings and not identifiers, because identifiers do not survive minification
 * and string literals do. A FIFTH would be worth adding the day the proving
 * ground grows a module that carries none of these — which is what the fourth
 * was: the collision bake is six thousand rows of numbers and would have gone
 * past all three of the others without a sentinel written for it.
 */
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");

/** Strings that may only exist behind `import.meta.env.DEV`. See the header. */
const SENTINELS = ["Proving Ground", "PG-Alpha", "PG-Level", "PG-Boxes"];

/**
 * Text the bundler emits. A `.wasm` or a `.png` cannot carry a sentinel.
 *
 * **`.map` is deliberately not in this list, and the omission is the one
 * judgement call in the file.** The server build emits sourcemaps with
 * `sourcesContent`, so `dist-server`'s maps carry `maps.ts` verbatim — the
 * `PROVING` definition included, because that file ships either way and the
 * definition is what the ternary chooses between. A sourcemap is debug
 * metadata about the source and not code anything runs, so matching it here
 * would fail every build for a string that is doing no harm. What the check is
 * for is the proving ground being REACHABLE, and a map file cannot make it so.
 */
const TEXT = /\.(js|mjs|css|html|json|webmanifest)$/;

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (TEXT.test(name)) out.push(p);
  }
  return out;
}

const roots = [dist, join(root, "dist-server")].filter((d) => existsSync(d));
if (roots.length === 0) {
  console.error(
    "check-proving: neither dist/ nor dist-server/ exists. Run this after a\n" +
      "  build, not before one — there is nothing to prove about an artefact\n" +
      "  that was not emitted.",
  );
  process.exit(1);
}
const files = roots.flatMap(walk);

const hits = [];
for (const file of files) {
  const text = readFileSync(file, "utf8");
  for (const s of SENTINELS) {
    if (text.includes(s)) hits.push(`${relative(root, file)}: ${s}`);
  }
}

if (hits.length > 0) {
  console.error(
    "check-proving: the DEV-only proving ground reached the production bundle.\n" +
      hits.map((h) => `  ${h}`).join("\n") +
      "\n\n" +
      "  `MAPS` in src/world/maps.ts must state the proving entry inside an\n" +
      "  `import.meta.env.DEV ? [...] : [...]` ternary, so the flag folds to a\n" +
      "  literal and Rollup can shake the generated modules. Anything that\n" +
      "  defers the decision to runtime keeps 400 kB of a map that is not a\n" +
      "  level in the bundle. See ENGINE_UPGRADE.md S0.",
  );
  process.exit(1);
}

console.log(
  `check-proving: ${files.length} emitted files across ` +
    `${roots.map((d) => relative(root, d)).join(" + ")}, no proving ground in any.`,
);
